use crate::models::{AnalysisResult, Severity};
use anyhow::Result;

pub fn to_json(result: &AnalysisResult) -> Result<String> {
    Ok(serde_json::to_string_pretty(result)?)
}

pub fn to_markdown(result: &AnalysisResult) -> String {
    let mut md = String::new();

    md.push_str("# Entra Least-Privilege Analysis Report\n\n");
    md.push_str(&format!(
        "**Tenant:** `{}`  \n**Analyzed at:** {}  \n**Users analyzed:** {}  \n**Assignments analyzed:** {}\n\n",
        result.tenant_id,
        result.analyzed_at.format("%Y-%m-%d %H:%M UTC"),
        result.user_count,
        result.assignment_count
    ));

    md.push_str("---\n\n## Summary\n\n");
    md.push_str("| Severity | Count |\n|---|---|\n");
    md.push_str(&format!("| Critical | {} |\n", result.summary.critical_count));
    md.push_str(&format!("| High | {} |\n", result.summary.high_count));
    md.push_str(&format!("| Medium | {} |\n", result.summary.medium_count));
    md.push_str(&format!("| Low | {} |\n", result.summary.low_count));
    md.push('\n');
    md.push_str(&format!(
        "Over-privileged accounts: **{}**  \nPermanent high-privilege accounts: **{}**  \nRoles without PIM protection: **{}**\n\n",
        result.summary.overprivileged_accounts,
        result.summary.permanent_high_privilege_accounts,
        result.summary.roles_without_pim
    ));

    if !result.gaps.is_empty() {
        md.push_str("---\n\n## Findings\n\n");
        for gap in &result.gaps {
            let icon = match gap.severity {
                Severity::Critical => "🔴",
                Severity::High => "🟠",
                Severity::Medium => "🟡",
                Severity::Low => "🔵",
                Severity::Informational => "⚪",
            };
            md.push_str(&format!(
                "### {} `{}`: {}\n\n",
                icon, gap.severity, gap.title
            ));
            md.push_str(&format!("**Description:** {}\n\n", gap.description));
            md.push_str(&format!("**Remediation:** {}\n\n", gap.remediation));
            if !gap.affected_principals.is_empty() {
                md.push_str("**Affected principals:**\n");
                for p in &gap.affected_principals {
                    md.push_str(&format!("- `{}`\n", p));
                }
                md.push('\n');
            }
        }
    }

    if !result.scores.is_empty() {
        md.push_str("---\n\n## Privilege Score Leaderboard (Top 10)\n\n");
        md.push_str("| Account | Score | Flags |\n|---|---|---|\n");
        for score in result.scores.iter().take(10) {
            let flags: Vec<String> = score.flags.iter().map(|f| format!("{:?}", f)).collect();
            md.push_str(&format!(
                "| `{}` | {} | {} |\n",
                score.user_principal_name,
                score.score,
                if flags.is_empty() { "-".to_string() } else { flags.join(", ") }
            ));
        }
        md.push('\n');
    }

    md.push_str("---\n\n*Generated by Entra Least-Privilege Analyzer (RayStudio)*\n");
    md
}

pub fn to_sarif_stub(result: &AnalysisResult) -> String {
    let rules: Vec<serde_json::Value> = result
        .gaps
        .iter()
        .map(|g| {
            serde_json::json!({
                "id": format!("{:?}", g.gap_type),
                "name": g.title,
                "shortDescription": { "text": g.description },
                "defaultConfiguration": { "level": match g.severity {
                    Severity::Critical | Severity::High => "error",
                    Severity::Medium => "warning",
                    _ => "note",
                }}
            })
        })
        .collect();

    let sarif = serde_json::json!({
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name": "entra-least-privilege-analyzer",
                    "version": "0.1.0",
                    "rules": rules
                }
            },
            "results": []
        }]
    });

    serde_json::to_string_pretty(&sarif).unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::{AnalysisSummary, GapType, PrivilegeFlag, PrivilegeScore, SecurityGap};
    use chrono::{TimeZone, Utc};

    fn sample_gap() -> SecurityGap {
        SecurityGap {
            gap_type: GapType::OverprivilegedAccount,
            severity: Severity::Critical,
            title: "Over-privileged account".to_string(),
            description: "desc".to_string(),
            affected_principals: vec!["alice@contoso.com".to_string()],
            remediation: "remediate it".to_string(),
        }
    }

    fn sample_result(gaps: Vec<SecurityGap>) -> AnalysisResult {
        AnalysisResult {
            tenant_id: "tenant-1".to_string(),
            analyzed_at: Utc.with_ymd_and_hms(2026, 7, 15, 12, 0, 0).unwrap(),
            user_count: 5,
            assignment_count: 3,
            scores: vec![PrivilegeScore {
                user_id: "u1".to_string(),
                user_principal_name: "alice@contoso.com".to_string(),
                score: 150,
                flags: vec![PrivilegeFlag::GlobalAdmin],
            }],
            summary: AnalysisSummary::from_gaps(&gaps, &[]),
            gaps,
        }
    }

    #[test]
    fn to_json_round_trips_core_fields() {
        let result = sample_result(vec![sample_gap()]);

        let json = to_json(&result).unwrap();
        let parsed: AnalysisResult = serde_json::from_str(&json).unwrap();

        assert_eq!(parsed.tenant_id, "tenant-1");
        assert_eq!(parsed.gaps.len(), 1);
    }

    #[test]
    fn to_markdown_includes_gap_and_score_details() {
        let result = sample_result(vec![sample_gap()]);

        let md = to_markdown(&result);

        assert!(md.contains("tenant-1"));
        assert!(md.contains("Over-privileged account"));
        assert!(md.contains("alice@contoso.com"));
        assert!(md.contains("| Critical | 1 |"));
    }

    #[test]
    fn to_markdown_omits_findings_section_when_there_are_no_gaps() {
        let result = sample_result(vec![]);

        let md = to_markdown(&result);

        assert!(!md.contains("## Findings"));
    }

    #[test]
    fn to_markdown_leaderboard_caps_at_ten_entries() {
        let mut result = sample_result(vec![]);
        result.scores = (0..15)
            .map(|i| PrivilegeScore {
                user_id: format!("u{i}"),
                user_principal_name: format!("user{i}@contoso.com"),
                score: i,
                flags: vec![],
            })
            .collect();

        let md = to_markdown(&result);

        assert_eq!(md.matches("user").count(), 10);
    }

    #[test]
    fn to_sarif_stub_always_emits_an_empty_results_array() {
        // Documents current (stub) behavior: rules are populated from gaps,
        // but `results` is always empty regardless of how many gaps exist.
        // Upgrading this to a real, populated SARIF file is planned as part
        // of the CI/CD gating Enterprise feature milestone, not here.
        let result = sample_result(vec![sample_gap()]);

        let sarif = to_sarif_stub(&result);
        let value: serde_json::Value = serde_json::from_str(&sarif).unwrap();

        assert_eq!(value["version"], "2.1.0");
        let rules = value["runs"][0]["tool"]["driver"]["rules"].as_array().unwrap();
        assert_eq!(rules.len(), 1);
        let results = value["runs"][0]["results"].as_array().unwrap();
        assert!(results.is_empty());
    }
}
