use crate::models::{AnalysisResult, Severity};
use anyhow::Result;

pub fn to_json(result: &AnalysisResult) -> Result<String> {
    Ok(serde_json::to_string_pretty(result)?)
}

pub fn to_markdown(result: &AnalysisResult) -> String {
    let mut md = String::new();

    md.push_str("# Entra Least-Privilege Analysis Report\n\n");
    md.push_str(&format!(
        "**Tenant:** `{}`  \n**Analyzed at:** {}  \n**Users analyzed:** {}  \n**Assignments analyzed:** {}\n\n",
        result.tenant_id,
        result.analyzed_at.format("%Y-%m-%d %H:%M UTC"),
        result.user_count,
        result.assignment_count
    ));

    md.push_str("---\n\n## Summary\n\n");
    md.push_str("| Severity | Count |\n|---|---|\n");
    md.push_str(&format!("| Critical | {} |\n", result.summary.critical_count));
    md.push_str(&format!("| High | {} |\n", result.summary.high_count));
    md.push_str(&format!("| Medium | {} |\n", result.summary.medium_count));
    md.push_str(&format!("| Low | {} |\n", result.summary.low_count));
    md.push('\n');
    md.push_str(&format!(
        "Over-privileged accounts: **{}**  \nPermanent high-privilege accounts: **{}**  \nRoles without PIM protection: **{}**\n\n",
        result.summary.overprivileged_accounts,
        result.summary.permanent_high_privilege_accounts,
        result.summary.roles_without_pim
    ));

    if !result.gaps.is_empty() {
        md.push_str("---\n\n## Findings\n\n");
        for gap in &result.gaps {
            let icon = match gap.severity {
                Severity::Critical => "🔴",
                Severity::High => "🟠",
                Severity::Medium => "🟡",
                Severity::Low => "🔵",
                Severity::Informational => "⚪",
            };
            md.push_str(&format!(
                "### {} `{}` — {}\n\n",
                icon, gap.severity, gap.title
            ));
            md.push_str(&format!("**Description:** {}\n\n", gap.description));
            md.push_str(&format!("**Remediation:** {}\n\n", gap.remediation));
            if !gap.affected_principals.is_empty() {
                md.push_str("**Affected principals:**\n");
                for p in &gap.affected_principals {
                    md.push_str(&format!("- `{}`\n", p));
                }
                md.push('\n');
            }
        }
    }

    if !result.scores.is_empty() {
        md.push_str("---\n\n## Privilege Score Leaderboard (Top 10)\n\n");
        md.push_str("| Account | Score | Flags |\n|---|---|---|\n");
        for score in result.scores.iter().take(10) {
            let flags: Vec<String> = score.flags.iter().map(|f| format!("{:?}", f)).collect();
            md.push_str(&format!(
                "| `{}` | {} | {} |\n",
                score.user_principal_name,
                score.score,
                if flags.is_empty() { "—".to_string() } else { flags.join(", ") }
            ));
        }
        md.push('\n');
    }

    md.push_str("---\n\n*Generated by Entra Least-Privilege Analyzer — RayStudio*\n");
    md
}

pub fn to_sarif_stub(result: &AnalysisResult) -> String {
    let rules: Vec<serde_json::Value> = result
        .gaps
        .iter()
        .map(|g| {
            serde_json::json!({
                "id": format!("{:?}", g.gap_type),
                "name": g.title,
                "shortDescription": { "text": g.description },
                "defaultConfiguration": { "level": match g.severity {
                    Severity::Critical | Severity::High => "error",
                    Severity::Medium => "warning",
                    _ => "note",
                }}
            })
        })
        .collect();

    let sarif = serde_json::json!({
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name": "entra-least-privilege-analyzer",
                    "version": "0.1.0",
                    "rules": rules
                }
            },
            "results": []
        }]
    });

    serde_json::to_string_pretty(&sarif).unwrap_or_default()
}
